# Generated by Django 5.0.7 on 2024-07-11 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_autor'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Autor',
            new_name='Autores',
        ),
    ]
