# Generated by Django 5.0.7 on 2024-07-11 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_categoria'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Categoria',
            new_name='Categorias',
        ),
    ]
